<template>
  <div class="px-4 py-2">
    <EasyDataTable :headers="headers" :items="items" alternating buttons-pagination>
      <template #item-setting="item">
        <v-btn variant="plain" icon="mdi-menu" @click=""></v-btn>
        <!-- <v-btn color="error" @click="">Delete</v-btn> -->
      </template>
    </EasyDataTable>
  </div>
</template>

<script>
import EasyDataTable from "vue3-easy-data-table"

const headers = [
  { text: "Name", value: "name", sortable: true },
  { text: "Telephone", value: "telephone", sortable: true },
  { text: "Company", value: "company", sortable: true },
  { text: "Last Update", value: "lastUpdate", sortable: true },
  { text: "Email", value: "email", sortable: true },
  // { text: "industrial", value: "industrial", sortable: true },
  // { text: "Source", value: "source" },
  // { text: "Owner", value: "owner" },
  // { text: "Added Date", value: "addDate" },
  // { text: "Edited Date", value: "editDate" },
  // { text: "Status", value: "status" },
  // { text: "Website", value: "website" },
  // { text: "Activity", value: "activity" },
  { text: "Setting", value: "setting" },
]

export default {
  data() {
    return {
      headers,
      items: [
        {
          name: "Stephen",
          telephone: "0123123",
          company: "AAA",
          lastUpdate: "2021-10-10",
          email: "",
          industrial: "",
          source: "",
          owner: "",
          addDate: "",
          editDate: "",
          status: "",
          website: "",
          activity: "",
        },
        {
          name: "Stephen",
          telephone: "0123123",
          company: "AAA",
          lastUpdate: "2021-10-10",
          email: "",
          industrial: "",
          source: "",
          owner: "",
          addDate: "",
          editDate: "",
          status: "",
          website: "",
          activity: "",
        },
        {
          name: "Stephen",
          telephone: "0123123",
          company: "AAA",
          lastUpdate: "2021-10-10",
          email: "",
          industrial: "",
          source: "",
          owner: "",
          addDate: "",
          editDate: "",
          status: "",
          website: "",
          activity: "",
        },
        {
          name: "Stephen",
          telephone: "0123123",
          company: "AAA",
          lastUpdate: "2021-10-10",
          email: "",
          industrial: "",
          source: "",
          owner: "",
          addDate: "",
          editDate: "",
          status: "",
          website: "",
          activity: "",
        },
        {
          name: "Stephen",
          telephone: "0123123",
          company: "AAA",
          lastUpdate: "2021-10-10",
          email: "",
          industrial: "",
          source: "",
          owner: "",
          addDate: "",
          editDate: "",
          status: "",
          website: "",
          activity: "",
        },
        {
          name: "Stephen",
          telephone: "0123123",
          company: "AAA",
          lastUpdate: "2021-10-10",
          email: "",
          industrial: "",
          source: "",
          owner: "",
          addDate: "",
          editDate: "",
          status: "",
          website: "",
          activity: "",
        },
        {
          name: "Stephen",
          telephone: "0123123",
          company: "AAA",
          lastUpdate: "2021-10-10",
          email: "",
          industrial: "",
          source: "",
          owner: "",
          addDate: "",
          editDate: "",
          status: "",
          website: "",
          activity: "",
        },
        {
          name: "Stephen",
          telephone: "0123123",
          company: "AAA",
          lastUpdate: "2021-10-10",
          email: "",
          industrial: "",
          source: "",
          owner: "",
          addDate: "",
          editDate: "",
          status: "",
          website: "",
          activity: "",
        },
        {
          name: "Stephen",
          telephone: "0123123",
          company: "AAA",
          lastUpdate: "2021-10-10",
          email: "",
          industrial: "",
          source: "",
          owner: "",
          addDate: "",
          editDate: "",
          status: "",
          website: "",
          activity: "",
        },
        {
          name: "Stephen",
          telephone: "0123123",
          company: "AAA",
          lastUpdate: "2021-10-10",
          email: "",
          industrial: "",
          source: "",
          owner: "",
          addDate: "",
          editDate: "",
          status: "",
          website: "",
          activity: "",
        },
      ],
    }
  },
  computed: {
    filteredList() {
      return this.contracts
    },
  },
}
</script>
